version: '3.8'

services:
  backend:
    build:
      context: ./pmt-backend2  # Chemin vers pmt-backend2
      dockerfile: Dockerfile
    container_name: pmt-backend2
    ports:
      - "8080:8080"
    environment:
      
      - DB_HOST=db
      - DB_NAME=pmt_db
      - DB_USERNAME=root
      - DB_PASSWORD=steve
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=stevetadesse0@gmail.com
      - MAIL_PASSWORD=xptw usin ohjm vhzu
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: steve
      MYSQL_DATABASE: pmt_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    container_name: pmt-frontend  # Nom du conteneur frontend
    build:
      context: ./pmt-frontend  # Répertoire contenant le Dockerfile pour le frontend
    ports:
      - "4200:81"  # Mappe le port 81 du conteneur au port 4200 de l'hôte
    networks:
      - app-network
    depends_on:
      - backend  # Attends que le backend soit prêt avant de démarrer

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
