version: '3.8'

services:
  backend:
    build:
      context: ./pmt-backend2  # Chemin mis à jour vers pmt-backend2
      dockerfile: Dockerfile
    container_name: pmt-backend2
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=pmt_db
      - DB_USERNAME=root
      - DB_PASSWORD=steve
    depends_on:
      db:
        condition: service_healthy  # Attendre que le service MySQL soit prêt avant de démarrer le backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: steve
      MYSQL_DATABASE: pmt_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
     healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psteve"]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 10s
      
  frontend:
    container_name: pmt-frontend
    build:
      context: ./pmt-frontend
    ports:
      - "4200:81"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy  # Attendre que le backend soit prêt avant de démarrer le frontend

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
